[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.84.2"
HUGO_THEME = "uBlogger"
HUGO_BASEURL = "https://ublogger.netlify.app"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
